name: Node.js CI

on: [push, pull_request]

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install Packages
      run: npm install
    - name: Install ESLinter
      run: npm install -g eslint     

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ./node_modules/eslint/bin/eslint.js src/function/*.js
    - run: ./node_modules/mocha/bin/mocha -r esm test/esm/*.test.js
    - run: ./node_modules/mocha/bin/mocha test/cjs/*.test.js  
