name: Publish
on:
  push:
    branches: 
    - release

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    strategy:
      matrix:
        node-version: [ 21.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - uses: actions/checkout@v4
    - name: Deno publish
      run: |
        npx jsr publish
    - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org' 
    - name: Configure npm
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        echo "always-auth=true" >> ~/.npmrc
        echo "strict-ssl=false" >> ~/.npmrc
        echo "loglevel=error" >> ~/.npmrc
        echo "fetch-retries=5" >> ~/.npmrc
        echo "fetch-retry-factor=10" >> ~/.npmrc
        echo "fetch-retry-mintimeout=20000" >> ~/.npmrc
        echo "fetch-retry-maxtimeout=120000" >> ~/.npmrc
        echo "cache-min=86400" >> ~/.npmrc
        echo "cache-max=86400" >> ~/.npmrc
        echo "cache=~/.npm" >> ~/.npmrc     
    - name: NPM publish
      run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}