name: Deploy
on:
  push:
    branches: 
    - release
  pull_request:
    branches: 
    - release

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    strategy:
      matrix:
        node-version: [ 21.x, 20.x, 18.x, 17.x, 16.x, 15.x]
    steps:
      - run: npm install
      - uses: actions/checkout@v4
      - run: npx jsr publish
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Notify success
        run: echo "Deployment successful!"
      - name: Notify failure
        if: failure()
        run: echo "Deployment failed!"
      - name: NPM publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Notify NPM publish success
        run: echo "NPM package published successfully!"
      - name: Notify NPM publish failure
        if: failure()
        run: echo "NPM package publish failed!"
      - name: Cleanup
        run: |
          echo "Cleaning up..."
          rm -rf node_modules
          rm -rf dist
          echo "Cleanup complete!"
